var indexedDB = window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB || window.shimIndexedDB;
var db;
var update = 0;

function initDB() {
    return new Promise((resolve, reject) => {
        const request = indexedDB.open("marmaDB", 1); // Update the version as needed

        const initialKnowledgeData = [
{ id: 'Start_Intro', order: 1, topic: 'Start', category: 'special', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Willkommen im Wissensbereich von GOM.', media: '', headline1: '', media1: '', text1: 'Im Wissensbereich von GOM findest du verschiedene Kapitel in denen Lektionen zu einem Thema zusammengefasst sind. ', headline2: '', media2: '', text2: 'Schließe Lektion nach Lektion ab und verfolge deinen Vortschritt auf der Übersichtsseite.', headline3: '', media3: '', text3: 'Die Themen sind gemischt, haben aber natürlich alle einen Bezug zu Yoga. Dabei bauen die Lektionen aufeinander auf, grundsätzlich kannst du dir aber die Themen suchen, die für dich gerade spannend sind. Sollten dir Lektionen zunächst etwas abstrakt erscheinen, kannst du diese zu einem späteren Zeitpunkt natürlich nocheinmal aufrufen, wenn Sie besser in deinen Lernfluss passen.', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'marmas_Intro', order: 2, topic: 'marmas', category: 'marmas', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'In diesem Kapitel geht es um Marmas.', media: '', headline1: '', media1: '', text1: 'Das Konzept der Marmas mag in der heutigen Zeit mit moderner Medizin etwas veraltet wirken, liefert aber nach wie vor gute Dienste. ', headline2: '', media2: '', text2: 'Diese besonderen Marma Punkte im Körper können uns dabei helfen ein besseres Körpergefühl zu entwickeln und uns in unserer Yogapraxis unterstützen. ', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'marmas_Basics', order: 3, topic: 'marmas', category: 'marmas', lesson: 'Basics', icon: 'start-icon.webp', content: {intro: 'Ein Marma ist ein bedeutsamer, vitaler Ort am Körper eines Menschen.', media: '', headline1: 'Herkunft', media1: '', text1: 'Marmas kommen aus der ayurvedischen Biologie. “Es sind die zentralen Stellen am menschlichen Körper, die sensitiv, verletztbar sind. Sie liegen offen da und sind durch Unfälle, Krankheit oder Angriffe besonders gefährdet. Verletzungen können zur invalidität führen, bzw. totbringend sein.” ¹', headline2: 'Marmas im Yoga-Kontext', media2: '', text2: 'In der Yogapraxis können uns die Marmapunkte helfen  unseren Körper wahrzunehmen.', headline3: '', media3: '', text3: 'Während es unmöglich ist alle Musklen in unserem Arm einzeln wahrzunehmen und anzusteuern ist es deutlich leichter zu denken "ich greife nach dem Glas". Das gelernte automatische Bewegungsmuster der Muskeln befähigt uns dann das Glas sicher zu greifen.', headline4: '', media4: '', text4: 'Genauso helfen uns die Marmapunkte die Haltungsmuster im Yoga besser einzuüben und wahrzunehmen. Mit einer guten Kenntniss der wichtigsten Punkte im Körper und einer guten Wahrnehmeung an diesen Stellen können Fehlhaltungen selbst erkannt und verbessert werden.', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: '1) Yoga Ein Weg für dich, Reinhard Bögele 1996, Seite 43'}  },
{ id: 'marmas_MarmaGruppen', order: 4, topic: 'marmas', category: 'marmas', lesson: 'Marma Gruppen', icon: 'marmas.webp', content: {intro: '', media: '', headline1: 'Sehnen Marma (Snāyu स्नायु)', media1: '', text1: 'Sehnen Marmas sind im Yoga die kraftvollen Halteorte. Sie sind der Ort für schnelle, dynamische Bewegung sowie auch für Entspannung.', headline2: 'Muskel Marma (Māṃsa मांस)', media2: '', text2: 'Im Yoga helfen uns die Muskel Marmas gezielt Orte zu enstpannen oder auszudehnen und zu strecken. Muskeln übernehmen die Feinmotorik.', headline3: 'Knochen Marma (Asthi अस्थि)', media3: '', text3: 'Knochen haben auch im Yoga eine stützende Funktion. Sie sind der Ansatzpunkt für die Sehnen.', headline4: 'Blutgefäß Marma (Sirā सिरा)', media4: '', text4: 'Im Yoga möchten wir Blut und Nervenbahnen nicht blockieren, sondern einen guten Fluss ermöglichen. Die Blutfluss Marmas helfen uns Blokaden zu erkennen und zu vermeiden.', headline5: 'Gelenk Marma (Sandhi सन्धि)', media5: '', text5: 'Ein Gelenk ist eine stabile Verbindung von zwei oder mehr Knochen.', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'marmas_funfacts', order: 5, topic: 'marmas', category: 'marmas', lesson: 'fun facts', icon: 'fact-icon.webp', content: {intro: 'Einige Fun-Facts zu Marmas', media: '', headline1: '', media1: '', text1: 'Marma wird im Sanskrit मर्म geschrieben. Die sprachliche Wurzel “mr" heißt sterben. Marman heißt unter anderem der Kern, das Herz einer Sache.', headline2: '', media2: '', text2: 'Es gibt insgesammt 107 Marmas die in 5 Gruppen unterteilt sind: Sehnen Marmas, Muskel Marmas, Knochen Marmas, Blutgefäß Marmas und Gelenk Marmas.', headline3: '', media3: '', text3: 'Zuerst ausführlich erwähnt wurden Marmas vom Chirurgen Sushruta ca 150 v. Chr. ', headline4: '', media4: '', text4: 'In der ayurvedisschen Medizin haben Marmas 7 Bereiche: 3 Doshas und 3 Gunas (Prakriti) und Purusha.', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'fuß_Intro', order: 6, topic: 'fuß', category: 'anatomy', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Der Fuß ist das Fundament für unseren Körper. Eine gute, gesunde Körperaltung beginnt also schon mit der richtigen Fußhaltung.', media: '', headline1: '', media1: '', text1: 'Im Yoga-Kontext ist der Fuß vergleichbar mit den Wurzeln eines Baumes: stützend und nährend. Diese stützende Rolle ist nicht nur in stehenden, sondern auch in sitzenden oder liegenden Haltungen wichtig.', headline2: '', media2: '', text2: 'Im nächsten Abschnitt lernen wir mehr über die Anatomie des Fußes.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'fuß_Anatomie', order: 7, topic: 'fuß', category: 'anatomy', lesson: 'Anatomie', icon: 'anatomy-icon.webp', content: {intro: 'Schauen wir uns den Fuß von den verschiedenen Seiten an:', media: '<iframe src="foot/anatomy_foot.html?footStyle=1"></iframe>', headline1: 'Obenansicht', media1: '<img src="foot/oberseite.png">', text1: 'Von der Obenansicht sehen wir gut die vier verschiedenen Bereiche: schwarz der Versenknochen, grün Fußwurzelknochen, blau die fünf Mittelfußknochen und rot die Zehenglieder.', headline2: 'Außenansicht', media2: '<img src="foot/ausenseite.png">', text2: 'In der Außenansicht (klein Zehen Seite) sehen wir, dass der Fuß nur am hinteren Versenknochen und erst wieder vorne am Ende des Mittelfußknochens auf dem Boden aufsteht. Am Vorderfuß stehen die Grundzehenglieder, die Mittelzehenglieder und die Endzehenglieder auf dem Boden.', headline3: 'Innenansicht', media3: '<img src="foot/innenseite.png">', text3: 'Auch in der Innenansicht (Großzehenseite) sehen wir, dass der Fuß auf dem hinteren Teil der Ferse und erst wieder vorne am Ende des Mittelfußknochens  auf dem Boden steht.', headline4: 'Untenansicht', media4: '<img src="foot/unterseite.png">', text4: 'Von unten betrachtet fällt der stabile Versenhöcker auf, der die Last des Körpers aufnehmen kann.', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'fuß_GelenkeimFuß', order: 8, topic: 'fuß', category: 'anatomy', lesson: 'Gelenke im Fuß', icon: 'leg-icon.webp', content: {intro: 'Das Fußgelenk ist die Verbindung zwischen Wadenbein und Fuß. Es gibt aber auch eine Vielzahl an Gelenken im Fuß. ', media: '', headline1: 'Gelenke der Fußwurzel', media1: '', text1: 'Neben den Gelenken zwischen den Zehengliedern gibt es auch gelenkige Verbindungen zwischen dem Versenknochen und dem Fußwurzelknochen, dem Sprungbein und dem Fußwurzelknochen, sowie dem Versenknochen und dem Sprungbein. Die einzelnen Fußwurzelknochen fungieren hier als zwei Fußwurzelpakete, da diese insich eher starr sind.', headline2: '', media2: '<iframe src="foot/anatomy_foot.html?footStyle=2"></iframe>', text2: 'Diese gelenkigen Verbindungen haben nur einen sehr kleinen Bewegungsspielraum und sind dafür verantwortlich, dass der Fuß in sich richtig zentriert gehalten werden kann.', headline3: 'Gelenke der Längsachse', media3: '', text3: 'Eine weitere Möglichkeit die Beweglichkeit des Fußes zu betrachten ist enlang der Längsachse des Fußes, also von der Verse bis zu den Zehengliedern.', headline4: '', media4: '<iframe src="foot/anatomy_foot.html?footStyle=3"></iframe>', text4: 'Entlang der Innenseite: Verse, Fußwurzelknochen, Mittelfußknochen der  4. + 5. Zehe mit Zehengrundlgliedern bis zu den Mittel- und Endgliedern. Auf der Außenseite des Fußes geht es entlang des Sprungbeins, über das Fußwurzelknochenpaket über die Mittelfußknochen bis zu den Zehengrund-, Mittel- und Endgliedern der Zehen 1 bis 3.', headline5: 'Verdrehungen im Fuß', media5: '', text5: 'Ziel ist es das meiste Gewicht hinten mittig auf den Fußhöcker der Ferse sowie etwas Gewicht vorne am Ende des Mittelfußknochen zu bekommen.', headline6: '', media6: '', text6: 'Wenn das Gewicht vor dem Fußhöcker auf dem Boden aufkommt, sinkt die vordere Verse, das Sprungbein und die Fußwurzelpakte ab und es entsteht der Plattfuß. Gewicht zu weit hinten am Versenhöcker kann zu einem Hohlfuß führen. Gewicht zu weit innen könnte einen Knick-Platt-Spreitsfuß oder einen Hallux Valgus hervorrufen. Gewicht zu weit außen führt zu instabilität und Umknicken und in der Folge zu Belastung der Bänder.*', outro: 'Probleme der Fußstellungen können sich bis oben zum Nacken auswirken. Auch Fehlstellungen von oben können sich nach unten auf den Fuß auswirken.', quote: '*Beschriebene Sachverhalte sind nicht als medizinischer Rat aufzufassen.'}  },
{ id: 'fuß_Wahrnehmungs-übung', order: 9, topic: 'fuß', category: 'anatomy', lesson: 'Wahrnehmungs- übung', icon: 'perception-icon.webp', content: {intro: '', media: '', headline1: '', media1: '', text1: '', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Gewebearten_Intro', order: 10, topic: 'Gewebearten', category: 'anatomy', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Der Menschliche Körper besteht aus vier Gewebetypen.', media: '', headline1: '', media1: '', text1: 'Im Folgenden lernen wir die vier Gewebetypen und Ihren aufbau bzw die Funktion kennen.', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Gewebearten_DievierGewebearten', order: 11, topic: 'Gewebearten', category: 'anatomy', lesson: 'Die vier Gewebearten', icon: 'tissue-icon.webp', content: {intro: 'Der Körper des Menschen hat grundsätzlich die gleichen Strukturen wie jeder Säugetier-Körper. Man kann vier Gewebetypen für den Aufbau des Körpers unterscheiden.', media: '', headline1: 'Binde- und Stützgewebe', media1: '', text1: 'Binde- und Stützgewebe hat, wie der Name verrät, eine Stützende funktion. Man findet es als Fett und Knochengewebe. Außerdemlockerem als kollagenes Bindegewebe mit belastbaren kollagenen Fasern aus Proteinen.', headline2: 'Muskelgewebe', media2: '', text2: 'Muskelgewebe ist das einzige Gewebe, welches kontrahieren kann → dadurch wird Bewegung erst möglich. Zum Arbeiten brauchen Muskeln als Brennstoff ATP (Adenosintriphosphat) und Sauerstoff. Sie bestehen zu 60 % aus Protein.', headline3: 'Epithelgewebe', media3: '', text3: 'Das Epithelgewebe bedeckt fast alle inneren und äußeren Körperflächen bzw. Drüsen. Man findet es in der Oberhaut und Lunge. Es übernimmt die Aufgaben Stoffabgabe, Schutz sowie Sekretion.', headline4: 'Nervengewebe', media4: '', text4: 'Das Nervengewebe ist anders aufgebaut als die anderen Gewebearten: Es besteht aus einer flüssigen, zähen, weißen Masse, ähnlich gegrillten Marshmallows. Es besteht aus Protein und Fett sowie einer bindegewebigen Hülle. Zu den Aufgaben zählt die Steuerung des Grund-Tonus der Muskeln und aller Funktionen (z.B. Gelenkstellung, Muskelkontraktion). Außerdem die Reizübertragung an das Gehirn.', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'yogas_Intro', order: 12, topic: 'yogas', category: 'yoga', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Beim Yoga dreht sich nicht alles nur um das rein Körperliche, also die Haltungen oder Bewegungsabläufe. Unter anderem hat Yoga auch eine mentale bzw. psychische Komponente. ', media: '', headline1: '', media1: '', text1: 'In diesem Abschnitt lernen wir kennen, wie wir besser auf uns und unsere Bedürfnisse achten könen.', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'yogas_Die4Yogas', order: 13, topic: 'yogas', category: 'yoga', lesson: 'Die 4 Yogas', icon: 'yoga-icon.webp', content: {intro: 'Aus Yogasicht gibt es vier Beziehungsqualitäten', media: '', headline1: 'ati (अति) ', media1: '', text1: 'viel, sehr, übermäßig, extrem', headline2: 'hīna (हीन)', media2: '', text2: 'ohne, leer sein von, zu wenig', headline3: 'mithyā (मिथ्या)', media3: '', text3: 'ohne, leer sein von, zu wenig', headline4: 'śam (शम्)', media4: '', text4: 'Wohlergehen, Wohlstand, Segen, Gesundheit, bzw. das passende', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: 'Im Yoga wollen wir über die Zeit ein Gefühl für das richtige bekommen.', quote: ''}  },
{ id: 'yogas_DasPassende', order: 14, topic: 'yogas', category: 'yoga', lesson: 'Das Passende', icon: 'check-icon.webp', content: {intro: 'Bei der Frage was gerade passend ist, sollte immer die aktuelle Ausgangssituation betrachtet werden.', media: '', headline1: 'Die Umstände stehen immer mit auf der Matte.', media1: '', text1: 'Hat man beispielsweise schlecht geschlafen, kann man ruhiger und aufmerksamer in die Übungen gehen, damit diese auch gelingen. Fühlt man sich fit und und voller Energie kann man etwas intensivere Haltungen zu probieren oder Haltungen länger halten.', headline2: '', media2: '', text2: 'Wenn man diese Umstände bewusst betrachtet, kann man einen passenden Umgang damit finden.', headline3: '', media3: '', text3: 'Außerdem lernen wir Ahimsa kennen. Eine Erinnerung "nicht feindselig" mit unserem Umfeld sowie mit uns selbst zu sein.', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'yogas_Ahiṃsā', order: 15, topic: 'yogas', category: 'yoga', lesson: 'Ahiṃsā', icon: 'peace-icon.webp', content: {intro: 'अहिंसा = nicht feindselig', media: '', headline1: '', media1: '', text1: 'Ahimsa ist eines der ethischen Regeln bzw. moralische Richtlinie im Yoga. Ahimsa ist keine konkrete Verhaltensregel. Das Gute soll verstärkt werden, das negative reduziert.', headline2: '', media2: '', text2: 'Gemeint ist die “nicht Feindseligkeit” gegenüber anderen, soll aber auch auf sich selbst übertragen werden. Ahimsa setzt sich zusammen aus a = nicht himsa = feindselig.', headline3: 'Beispiele für die Feindseligkeit gegenüber anderen:', media3: '<ul><li>Gewalt</li><li>Hass</li><li>Missgunst</li><li>Lüge</li></ul>', text3: '', headline4: 'Beispiele für die Feindseligkeit gegenüber sich selbst:', media4: '<ul><li>Hunger haben aber nicht essen</li><li>Müde sein aber nicht schlafen</li><li>über sich selbst ärgern</li><li>sich selbst unnötigen Schmerz zufügen</li></ul>', text4: '', headline5: 'Ahiṃsā in der Yoga Praxis', media5: '', text5: 'Auch in der Yogapraxis wollen wir nicht feindselig mit uns und unserem körper sein. Wir wollen keinen Ehrgeiz, keine überbelastung und Schmetzen, keine enttäuschung oder Wut wenn etwas nicht klappt.', headline6: '', media6: '', text6: 'Im Yoga kümmern wir uns um um unser Wohlbefinden und wissen, dass Yoga eine Lebensaufgabe ist.', outro: '', quote: ''}  },
{ id: 'Sehnen Marmas_Intro', order: 16, topic: 'Sehnen Marmas', category: 'marmas', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'In diesem Kapitel lernen wir die Sehnen Marmas kennen, die erste der 5 Marmagruppen.', media: '', headline1: '', media1: '', text1: 'Du darfst dich nicht nur über Hintergründe zu den Kraftorten freuen, sondern kannst auch etwas über die Sehnen selbst erfahren.', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Sehnen Marmas_Basics', order: 17, topic: 'Sehnen Marmas', category: 'marmas', lesson: 'Basics', icon: 'start-icon.webp', content: {intro: 'Sehnen Marmas sind im Yoga die kraftvollen Halteorte. Sie sind der Ort für schnelle dynamische Bewegung sowie für Entspannung.', media: '', headline1: 'Was sind Sehnen?', media1: '', text1: 'Sehnen bestehen aus straffen Bingewebe und aus kollagenen Fasern. Sie haben eine hohe Zugfestigkeit und dehnen sich nur sehr wenig. Sehnen sind die Verbindung zwischen Knochen und Muskeln und übertragen die Kraft.', headline2: 'Eigenschaften der Sehnen im Yoga-Kontext', media2: '', text2: 'Mit Sehnen können z.B. die Eigenschaften stabil, schnell und glatt verknüpft werden.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Sehnen Marmas_YogaPraxis', order: 18, topic: 'Sehnen Marmas', category: 'marmas', lesson: 'Yoga Praxis', icon: 'yoga-icon.webp', content: {intro: 'Im Yoga wollen wir uns die Kraftvole stabile Struktur der Sehnen zu nutze machen.', media: '', headline1: 'Haltearbeit', media1: '', text1: 'Oft wird die Haltearbeit von unseren Muskeln übernommen, meist unbewust. In Yoga Haltungen wollen wir die Muskeln so viel wie möglich entspannen und die Haltearbeit über Knochenstütze und die Sehnen leisten.', headline2: 'Kraftort', media2: '', text2: 'Sehnen sind wichtige Kraftorte und stützen den Körper. Angespannt sind sie bereit die Kraft freizusetzten und kraftvolle, schnelle, dynamische Bewegungen auszulösen.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Übung_Intro', order: 19, topic: 'Übung', category: 'yoga', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Yoga üben ist leider manchmal mit Rückschlägen verbunden.', media: '', headline1: '', media1: '', text1: 'Übungen die schon gut geklappt haben funktionieren plötzlich nicht mehr so gut. Plötzlich meldet sich ein zwicken, das man vorher nicht gespürt hat.', headline2: '', media2: '', text2: 'In diesem Abschnitt schauen wir uns an wie wir mit solchen Erfahrungen umgehen können.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Übung_Schwankungen', order: 20, topic: 'Übung', category: 'yoga', lesson: 'Schwankungen', icon: 'graph-icon.webp', content: {intro: 'Beim Üben ist es normal, wenn etwas mal besser und mal wieder schlechter klappt.', media: '', headline1: '', media1: '', text1: 'Wenn es einmal funktioniert hat - und sei es „nur“ unter Anleitung – ist diese Erfahrung ein wichtiger Schritt. Ein wichtiger Zwischenschritt beim Übergang von „Ich kann mir gar nicht vorstellen, wie das gehen soll“ zu „Jetzt klappt es schon gut“.', headline2: '', media2: '', text2: 'Mit der Zeit bekommt man Schritt für Schritt ein besseres Gefühl und Verständniss wie es sich anfühlen muss. ', headline3: '', media3: '', text3: 'Auch das Nervensystem lernt das neue Muster. Dabei ist es völlig normal, dass man immer wieder in ein altes Muster zurückfällt. Über die Zeit wird sich mit konstantem Üben das neue Muster festigen.', headline4: '', media4: '', text4: 'Yoga ist keine Disziplin, bei der man ein bestimmtes Ziel erreichen möchte und mit Erreichen des Ziels dann diese Disziplin gemeistert hat. Viel mehr ist es ein konstantes Beschäftigen mit sich und seinem Körper und den ständigen Veränderungen.', headline5: '', media5: '', text5: 'Das konstante Bewerten des eigenen „Fortschritts“ ist dabei eher hinderlich. Scheinbare Rückschritte lösen frustration aus, während eigentlich ein großer Vortschritt erziehlt worden ist. ', headline6: '', media6: '', text6: 'Das Bewusst machen und Reflektieren des aktuellen Ist-Zustandes ohne zu Bewerten ist erwünscht. Auch diese Herangehensweise braucht viel Übung. ', outro: 'Was zunächst also wie eine Verschlechterung wirkt ist eigentlich ein großer Vortschritt.', quote: ''}  },
{ id: 'Übung_Verschlechterung', order: 21, topic: 'Übung', category: 'yoga', lesson: 'Verschlechterung', icon: 'personal-growth-icon.webp', content: {intro: 'Yoga ist ein aufdeckendes Verfahren.', media: '', headline1: '', media1: '', text1: 'Wenn eine Übung mit der Zeit schlechter funktioniert oder auf einmal ein Zwicken, Druck oder Schmerzen spürbar sind muss das nicht bedeuten, dass man sich beim Üben verschlechtert hat. Vielmehr sollte geprüft werden, ob das Thema schon vorher existiert hat und nun erst Bewust geworden ist.', headline2: '', media2: '', text2: 'Manchmal wird eine Fehlhaltung an einer Körperstelle durch eine Fehlhaltung an anderer Stelle kompensiert. Hat man es nun geschafft eine der Fehlhaltungen zu korrigieren, kann es sein, dass sich plötzlich eine ganz andere Körperstelle meldet. ', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Übung_Kopfsache', order: 22, topic: 'Übung', category: 'yoga', lesson: 'Kopfsache', icon: 'relax-icon.webp', content: {intro: 'Ca. 60 % von Yoga findet im Kopf statt', media: '', headline1: '', media1: '', text1: 'Es ist sehr wichtig die Orte im Körper zu kennen, damit man dort hindenken, sie spüren und ansteuern kann. Am Anfang ist es schon ein großer Gewinn, einordnen zu können, wenn sich ein Ort von selbst meldet.', headline2: '', media2: '', text2: 'Deshalb ist es gut sich mit den Marmas zu beschäftigen. Wenn dabei manche Marmas in den Vordergrund rücken und andere vielleicht etwas in den Hintergrund, ist das vollkommen in Ordnung. Es gibt hier keinen fest vorgeschriebenen Zeitplan, nach dem alle Marmas erfahren worden sein sollten. Die Erfahrungen entwickeln sich mit der Zeit und bei jedem individuell. Man lernt ein Leben lang.', headline3: '4 Schritte für die Durchführung einer Übung', media3: '<ol><li>An den Ort denken.</li><li>Prüfen, ist der Ort erreicht?</li><li>Richtung denken.</li><li>Prüfen, richtige Richtung erreicht? </li></ol>', text3: '', headline4: '', media4: '', text4: 'Fokussierte Aufmerksamkeit an ein oder zwei Orten, der Rest organisiert sich mit!', headline5: '', media5: '', text5: 'Tipp: Oft ist es hilfreich das Gehirn beim Wahrnehmen "entspannt zurückzulehnen". Sich hineinzusteigern beeinträchtigt die Erfahrung.', headline6: '', media6: '', text6: '', outro: 'Man muss es denken können.', quote: ''}  },
{ id: 'Übung_3Sekunden-Regel', order: 23, topic: 'Übung', category: 'yoga', lesson: '3 Sekunden-Regel', icon: 'wait-sandclock-icon.webp', content: {intro: 'Laut dem Münchner Hirnforscher Ernst Pöppel strukturiert unser Bewusstsein die Wahrnehmung der Gegenwart in „Drei-Sekunden-Einheiten“, auch bekannt als die Drei-Sekunden-Regel.', media: '', headline1: '', media1: '', text1: 'Das Heißt nur alle 3 Sekunden macht unser Gehirn eine "Bestandsaufname" der aktuellen Sinnenseindrücke.', headline2: '', media2: '', text2: 'Für Yoga heißt das, damit Eindrücke wirklich erfasst und gespeichert werden können sollte dem Bewustsein Zeit gegeben werden diese zu erfassen.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: 'Pöppel,  E.  (1997).  Grenzen des Bewusstseins: wie kommen wir zur Zeit, und wie entsteht Wirklichkeit?.  Deutschland:  Insel-Verlag.'}  },
{ id: 'Verletzungen_Verletzung', order: 24, topic: 'Verletzungen', category: 'yoga', lesson: 'Verletzung', icon: 'medical-briefcase-icon.webp', content: {intro: 'Körperliche Einschränkungen wie z. B. Verletzungen bedeuten nicht unbedingt, dass man mit Yoga pausieren muss.', media: '', headline1: 'Schonen', media1: '', text1: 'Wird ein Körperteil verletzt, muss dieser geschont werden. Allerdings kann der Körperteil unter dem Gesichtspunkt der Schonung betrachtet werden. Die Übungen werden dementsprechend sorgfältig ausgewählt und angepasst.', headline2: 'Yoga findet zuerst im Kopf statt', media2: '', text2: 'Der verletzte Körperteil kann beim Wahrnehmen mit einbezogen werden. Mit den gesunden Körperteilen kann weiter Yoga geübt werden. Über Spiegelneuronen kann der verletzte Körperteil auch von Übungen mit dem gesunden Körperteil profitieren, also mit der gesunden Seite zusammen lernen. Man kann dann auch von einer Lehrer- und einer Schülerseite sprechen.', headline3: 'Sekundärer Krankeihtsgewinn', media3: '', text3: 'Sekundärer Krankeihtsgewinn beschreibt, wenn durch eine Verletzung andere positive Effekte auftreten. Widmet man einem bestimmten Marma durch eine Verletzung besonders viel Aufmerksamkeit, kann dieses nach der Verletzung sogar stärker sein als das nicht verletzte Pendant. ', headline4: 'Wichtig', media4: '<ul><li>Yoga sollte nicht aus Pflicht getan werden!</li><li>Yoga ist auch Mittel zur Regeneration bei Krankheit, Stress, Belastung.</li><li>Yoga Unterstützungsmittel nutzen (Klötze, Rolle, Decke etc.).</li><li>Keine Überbeanspruchung oder Ehrgeiz.</li><li>Beachten der 4 Yogas: passend, verkehrt, zu viel, zu wenig</li></ul>', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: '1) Ertelt, D., Small, S., Solodkin, A., Dettmers, C., McNamara, A., Binkofski, F., & Buccino, G. (2007). Action observation has a positive impact on rehabilitation of motor deficits after stroke. NeuroImage, 36 Suppl 2, T164-173.'}  },
{ id: 'Muskel Marmas_Intro', order: 25, topic: 'Muskel Marmas', category: 'marmas', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Die zweite Marmagruppe sind die Muskel Marmas über die du in diesem Kapitel etwas erfährst.', media: '', headline1: '', media1: '', text1: 'Außerdem gibt es noch etwas über die Funktionsweise von Muskeln und Muskelgewebe zu erfahren.', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Muskel Marmas_Basics', order: 26, topic: 'Muskel Marmas', category: 'marmas', lesson: 'Basics', icon: 'start-icon.webp', content: {intro: 'Im Yoga helfen uns die Muskelmarmas gezielt Orte zu enstpannen oder auszudehnen und zu strecken. Muskeln übernehmen die Feinmotorik.', media: '', headline1: 'Was sind Muskeln?', media1: '', text1: 'Muskeln bestehen haptsächlich aus zwei Arten von Musklefaser: tonische Fasern für langanhaltende Haltearbeit und phasische Fasern für schnelle, kraftvolle Bewegungen.', headline2: 'Eigenschaften der Muskeln im Yoga-Kontext', media2: '', text2: 'Attribute der Muskeln sind üblicherweise fest, kompakt, hart oder locker und weich.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Muskel Marmas_Muskelgewebe', order: 27, topic: 'Muskel Marmas', category: 'marmas', lesson: 'Muskelgewebe', icon: 'muscles-icon.webp', content: {intro: 'Die Skeletmuskulatur hält das Skelett zusammen bzw. gibt diesem Stabilität.', media: '', headline1: 'Aufbau', media1: '', text1: 'Die Verbindung von Knochen und Muskel bilden die Sehnen. Knochen sowie Muskeln werden von einer Haut umhüllt (Knochen-/ Muskelhaut), hieran sind Bänder (bindegewebige Haut) sowie äußerst stabile Sehnen (-platten) kompakt verwachsen.', headline2: 'Muskelfasern', media2: '<p>Muskelfasern können in zwei (Haupt-)Typen unterschieden werden.</p><p>Typ 1 sind die tonischen Fasern. Sie können langanhaltende Haltearbeit leisten und ermüden dabei nur langsam. Die Fasern haben eine rote Färbung.</p><p>Typ 2 sind die phasischen Fasern. Diese Fasern arbeiten schnell und kraftvoll, ermüden aber schnell. Die Fasern haben eine eher weiße Färbung.</p><p>Im Yoga wollen wir vor allem Muskeln mit einem hohen Anteil an tonischen Fasern nutzen, um mit wenig Kraftaufwand lange in den Übungen verharren zu können.</p>', text2: '', headline3: 'Aufgabe', media3: '', text3: 'Ein Muskel kann jeweils nur seine einzige bestimmungsgemäße Funktion ausführen. So muss es für verschiedene Funktionen verschiedene, entgegengesetzte Muskeln geben (Agonist + Antagonist). Zum Besipiel wird für die Armstreckung der Triezeps angezogen (Strecker) für die Beugung des Arms wird der Bizeps (Beuger) angezogen. Ein Muskel kann sich nicht von sich aus wieder strecken. Es braucht den Gegenspieler, bzw. die Schwerkraft.', headline4: 'Bewegung der Muskelfasern', media4: '<iframe src="mucle marma/muscle contraction.html"></iframe>', text4: 'Wird ein Muskel angespannt, zieht sich das Muskelgewebe zusammen. Wird der Gegenspieler Muskel angespannt, dehnt sich der Muskel und die Muskelphasern.', headline5: '', media5: '', text5: 'Im Yoga liegt das Interesse vor allem an den Streckmuskeln. ', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Muskel Marmas_Muskelspannung', order: 28, topic: 'Muskel Marmas', category: 'marmas', lesson: 'Muskelspannung', icon: 'muscles-icon.webp', content: {intro: 'Musklen haben immer eine Grundspannung, selbst beim Schlafen (Muskeltonus)', media: '', headline1: '', media1: '', text1: 'Die Muskelspannung wird von den Muskelspindeln gemessen. Muskelspindeln sind Sinnesorgane in den Muskeln, die den Dehnungszustand bzw. die Muskelspannung der Skelettmuskulatur erfassen. ', headline2: '', media2: '', text2: 'Wird ein Muskel stimuliert, wird die Muskelpannung lokal gemessen und vom Gehirn reguliert. Beispiel ist das Füllen eines Gefäßes unter dem Wasserhahn. Das zusätzliche Gewicht führt zu einer Spannungsänderung im Muskel. Das Gehirn reguliert den zusätzlichen Kraftbedarf und das Gefäß kann weiterhin gehalten werden.', headline3: '', media3: '', text3: 'Der Ruhetonus beschreibt die Grundspannung eines Muskles, welcher im Normalfall immer vorhanden ist. Im Yoga versuchen wir einen Tonus zu erreichen, bei dem Gelenke ohne Druck, Muskeln ohne zu starkem Zerren und die Blutgefäße frei sind.', headline4: 'Muskelspannung an Psyche und Sozieles gekoppelt', media4: '<p>Stressfaktoren oder Krankheit können sich auf Muskelspannung auswirken:</p><ul><li>depressive Stimmung: Tonus reduziert – schlaff</li><li>ängstliche Stimmung: Tonus erhöht – angespannt</li><li>ständig leichtes Zittern (Spannung) im Körper, auch bei nicht gezielten Bewegungen</li></ul>', text4: '', headline5: 'Wichtig aus yogischer Sicht', media5: '', text5: 'Nur zart an Muskeln ziehen, Stress enthalten, ein Zuviel vermeiden. ', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Muskel Marmas_funfacts', order: 29, topic: 'Muskel Marmas', category: 'marmas', lesson: 'fun facts', icon: 'fact-icon.webp', content: {intro: '', media: '', headline1: '', media1: '', text1: 'Ein Mensch hat 656 Muskeln. Der stärkse Muskel im menschlichen Körper ist der Kaumuskel.', headline2: '', media2: '', text2: 'Auch im Schlafen und Sitzen bleibt ein Grund-Tonus der Muskeln erhalten, dieser wird nur bei einer großen Narkose ausgeschaltet (einschließlich Atemmuskulatur → Beatmung erforderlich).', headline3: '', media3: '', text3: 'Der Herzmuskel ist eine modifizierte Form der Skeletmuskulatur. Auch die Zungenmuskulatur gehört zur Skeletmuskulatur. Skeletmuskulatur wird auch als quergestreifte Muskulatur bezeichnet.', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Knochen Marmas_Intro', order: 30, topic: 'Knochen Marmas', category: 'marmas', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Die dritte Familie der Marmas sind die Knochen Marmas.', media: '', headline1: '', media1: '', text1: 'Auch hier schlagen wir die Brücke von der Marmatheorie zu modernen Erkenntnissen. So kannst du ein bisschen etwas über den Aufbau eines Knochens erfahren.', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Knochen Marmas_Basics', order: 31, topic: 'Knochen Marmas', category: 'marmas', lesson: 'Basics', icon: 'start-icon.webp', content: {intro: 'Knochen haben auch im Yoga eine stützende Funktion. Sie sind der Ansatzpunkt für die Sehnen.', media: '', headline1: 'Aufbau', media1: '', text1: 'Knochen bestehen aus ca 45% anorganischen Stoffen, außerdem aus ca. 25% Wasser und 30 % organischen Stoffen. Es ist also lebendes Gewebe, welches ebenfalls Veränderungen ausgesetzt ist, wenn auch nur sehr langsam.', headline2: 'Eigenschaften der Knochen im Yoga-Kontext', media2: '', text2: 'Knochen werden meist mit den Attributen schwer, fest und hart beschrieben. Qualitäten sind geführt, stabil, gestützt.', headline3: '', media3: '<ul><li>Knochen sind lebendig</li><li>Knochen sind Koordinationsorte</li><li>Knochen bilden Gelenke</li><li>Knochen sind unsere Stütze</li></ul>', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Knochen Marmas_Knochengewebe', order: 32, topic: 'Knochen Marmas', category: 'marmas', lesson: 'Knochengewebe', icon: 'bone-icon.webp', content: {intro: 'Knochengewebe ist besonders hartes Gewebe, das aus vielen einzelnen Knochen das Skelett bildet.', media: '', headline1: '', media1: '', text1: 'Knochen sind umhüllt von einer Knochenhaut mit vielen Blutgefäßen (Periost). Diese ist sehr schmerzempfindlich, der Knochen selbst allerdings nicht.', headline2: '', media2: '', text2: 'Knochengewebe besteht aus ener festen Struktur, der Knochenmatrix. Diese besteht aus kollagenen Fasern. Die Knochenmatrix wird durch anorganische Kristalle verfestigt. In der Matrix finden sich Knochenzellen (Osteozyten), die über die Knochenkanälchen miteinander verbunden sind.', headline3: '', media3: '', text3: 'Der Knochen selbst lebt und ist durchblutet. Zur Erhaltung der Belastbarkeit und Stützung des Körpers  finden ständige Aufbau-, Umbau- und Anbau-Prozesse statt. Im Alter verlangsamen sich diese Prozesse. Der Erhalt der Knochenstabilität kann durch Druck und Zugbelasung erhalten bzw. verbessert werden.', headline4: '', media4: '', text4: 'Bei einem Bruch wird nach kurzer Zeit zunächst überschießendes Knochenmaterial Aufgebaut. Die Beule aus Knochengewebe wird späterer durch Osteoklasten wieder abgebaut bis zur Anpassung an die ursprüngliche Form des Knochens.', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Blutgefäß Marmas_Intro', order: 33, topic: 'Blutgefäß Marmas', category: 'marmas', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'In dieem Abschnitt betrachten wir die Blutgefäß Marmas.', media: '', headline1: '', media1: '', text1: 'Die Blutgefäß Marmas in diesem Abschnitt sind etwas abstrakter, als die Marmas die wir schon kennengelernt haben. Die Definition ist etwas weiter gefasst als der reine Blutfluss.', headline2: '', media2: '', text2: 'Der Blutfluss ist einer der wichtigsten Aspekte des Marmas, daher findest du hier gleich mehrere Lektionen zu dem Thema.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Blutgefäß Marmas_Basics', order: 34, topic: 'Blutgefäß Marmas', category: 'marmas', lesson: 'Basics', icon: 'start-icon.webp', content: {intro: 'Im Yoga möchten wir Blut und Nervenbahnen weder von außen noch durch Muskelspannung quetschen und blockieren, sondern einen guten Fluss ermöglichen. Die Blutfluss Marmas helfen uns Blokaden zu erkennen und zu vermeiden.', media: '', headline1: 'Bedeutung', media1: '', text1: 'Unter Blutgefäß Marmas sind nicht nur Venen und Aterien sondern auch das Lymphische System, Organe und die Nervenbahnen zusammengefasst.', headline2: 'Eigenschaften der Blut-, Nerven- und Lymphsysteme im Yoga-Kontext', media2: '', text2: 'Wünschenswerte Eigenschaften bei den Blutfluss Marmas sind fließend, klar, weich und flüssig.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Blutgefäß Marmas_Arterien', order: 35, topic: 'Blutgefäß Marmas', category: 'marmas', lesson: 'Arterien', icon: 'drop-icon.webp', content: {intro: 'Arterien, auch Schlagadern genannt, dienen dem Transport des Blutes vom Herzen in das Gewebe. Arterien transportieren sauerstoffreiches Blut.', media: '', headline1: 'Aufbau', media1: '<ul><li>Arterien bestehen aus drei Schichten.</li><li>Arterien haben generell eine dickere Wand als Venen, weil in ihnen ein höherer Druck herrscht.</li><li>Die mittlere Schicht (Media) enthält glatte Muskulatur und/oder elastisches Bindegewebe. Diese dicke mittlere Schicht ist bei den Venen kaum ausgeprägt.</li></ul>', text1: '', headline2: 'Bluttransport', media2: '', text2: 'Eine vom Herzen erzeugte Druckwelle treibt den Bluttransport in den Arterien an. ', headline3: '', media3: '', text3: 'Strömt Blut in das Gefäß, dehnt die Pulswelle zunächst die Arterienwand, bevor diese sich wieder zusammenzieht. Der durch die Herzpumpe erzeugte diskontinuierliche Blutstrom wird in eine kontinuierliche Strömung umgewandelt. → Windkesselfunktion', headline4: 'fun facts', media4: '', text4: 'In den Arterien ist das Pulsieren des Herzschlags spürbar, weshalb sie auch Schlag- oder Pulsadern genannt werden.', headline5: '', media5: '', text5: 'Bekannteste Arterie ist die Aorta (Hauptschlagader). Das Herz pumpt das Blut aus der linken Herzkammer direkt in dieses dickste aller Gefäße (bis zu 3cm dick).', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Blutgefäß Marmas_Venen', order: 36, topic: 'Blutgefäß Marmas', category: 'marmas', lesson: 'Venen', icon: 'drop-icon.webp', content: {intro: 'Venen, auch Blutadern genannt, dienen der Speicherung und dem Rücktransport des Blutes zum Herzen. Venen transportieren sauerstoffarmens Blut.', media: '', headline1: 'Aufbau', media1: '<ul><li>Venen bestehen aus drei Schichten.</li><li>Die mittlere Schicht (Media) ist bei den Venen kaum ausgeprägt, da ein geringer Druck herscht.</li><li>Bein- und Armvenen besitzen Venenklappen. Diese ventielfunktion sorgt dafür, dass das Blut zum Herzen hin fließt, bzw. verhindern Rückfluss/Versacken des Blutes.</li></ul>', text1: '', headline2: 'Bluttransport', media2: '', text2: 'Die Muskelpumpe ist mit Unterstützung der Venenklappen die Antriebskraft des Blutflusses in den Venen. ', headline3: '', media3: '', text3: 'Die Venen sind die Blutgefäße, die Blut aus der Peripherie des Körpers, beispielsweise den Beinen entgegen der Schwerkraft zurück zum Herzen transportieren. ', headline4: '', media4: '', text4: 'Damit das Blut nicht „in den Beinen versackt“, ist ein gut aufeinander abgestimmtes System aus Venenklappen und Muskelpumpe erforderlich. Venenklappen haben eine Ventilfunktion, das bedeutet, dass sie nur den Blutfluss in Richtung Herz zulassen. In der umgebenden Skelettmuskulatur verdicken sich die Muskelbäuche und drücken die dazwischenliegenden Venen zusammen → Muskelpumpe.', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Blutgefäß Marmas_Kapillaren', order: 37, topic: 'Blutgefäß Marmas', category: 'marmas', lesson: 'Kapillaren', icon: 'drop-icon.webp', content: {intro: 'Die Kapillaren, auch Haargefäße genannt, bilden den Übergang von den Arterien zum venösen System. ', media: '', headline1: '', media1: '', text1: 'Im Bereich der Kapillaren, auch Kapillargebiet genannt, erfolgt der Gas- und Stoffaustausch.', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Nervensystem_Intro', order: 38, topic: 'Nervensystem', category: 'anatomy', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Das Nervensystem ist spielt bei allen Vorgängen in unserem Körper eine wichtige Rolle.', media: '', headline1: '', media1: '', text1: 'Im Folgenden lernen wir drei verschieden Varianten kennen, wie der Aufbau des Nervensystems beschrieben werden kann.', headline2: '', media2: '', text2: 'Je nachdem Welche Funktion des Nervensystems beschrieben wird ist es Hilfreich das richtige Konzept zu kennen.', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Nervensystem_TopografischerAufbau', order: 39, topic: 'Nervensystem', category: 'anatomy', lesson: 'Topografischer Aufbau', icon: 'cell-molecule-icon.webp', content: {intro: '', media: '', headline1: 'Zentrales Nervensystem ', media1: '', text1: 'Besteht aus dem Gehirn und Rückenmark und ist verantwortlich für die Zentrale Reizverarbeitung.', headline2: 'Peripheres Nervensystem', media2: '', text2: 'Besteht aus Nerven in Muskeln und Organen bzw. ist die Verbindung der Organe mit dem zentralen Nervensystem. ', headline3: 'Funktionsweise', media3: '', text3: 'Reize werden über Rezeptoren in der Peripherie wahrgenommen und über das periphere Nervensystem an das zentrale Nervensystem weitergegeben (Afferenz = Reizaufnahme).', headline4: '', media4: '', text4: 'Im zentralen Nervensystem werden die Reize verarbeitet (d.h. integriert und koordiniert).', headline5: '', media5: '', text5: 'Aus dem zentralen Nervensystem gelangt z.B. der motorische Befehl dann über das periphere Nervensystem zurück zum Muskel (Efferenz = Reizbeantwortung).', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Nervensystem_FunktionalerAufbau', order: 40, topic: 'Nervensystem', category: 'anatomy', lesson: 'Funktionaler Aufbau', icon: 'cell-molecule-icon.webp', content: {intro: '', media: '', headline1: 'somatisches Nervensystem', media1: '', text1: 'Dient der willkürlichen oder bewussten motorischen Ansteuerung der Skelettmuskulatur bzw. der Wahrnehmung der Körperperipherie.', headline2: 'vegetativen Nervensystem', media2: '', text2: 'Unbewusste und unwillkürliche Steuerung der inneren Organe und lebenswichtiger Vorgänge z.B. Verdauung, Blutkreislauf, Atmung, Körpertemperatur.', headline3: '', media3: '', text3: 'Die Aufgabe ist das Gleichgewicht der physiologischen Körperfunktionen aufrechtzuerhalten.', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Nervensystem_vegetativesNervensystem', order: 41, topic: 'Nervensystem', category: 'anatomy', lesson: 'vegetatives Nervensystem', icon: 'intestine-icon.webp', content: {intro: 'Das vegetative Nervensystem kann weiter untergliedert werden in:', media: '', headline1: 'sympathisches Nervensystem (Sympathikus)', media1: '', text1: 'Verantwortlich für erhöhte Leistungsbereitschaft sowie den Abbau von Energiereserven („fight and flight“)', headline2: 'parasympathisches Nervensystem (Parasympathikus)', media2: '', text2: 'Steuert die Regeneration des Organismus und Aufbau von Energiereserven („rest and digest“)', headline3: 'enterisches Nervensystem', media3: '', text3: 'Übernimmt die Steuerung der Magen-Darm-Funktionen.', headline4: 'Yoga Kontext', media4: '', text4: 'Die Idee im Yoga ist es geziehlt mit Übungen / Aktivität den Sympathikus ansteuern, um dann über den Parasympathikus die Regeneration zu steigern. ', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Gelenk Marmas_Into', order: 42, topic: 'Gelenk Marmas', category: 'marmas', lesson: 'Into', icon: 'intro-icon.webp', content: {intro: 'Die letzte Marmagruppe die wir kennenlernen sind die Gelenk Marmas', media: '', headline1: '', media1: '', text1: '', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Gelenk Marmas_Basics', order: 43, topic: 'Gelenk Marmas', category: 'marmas', lesson: 'Basics', icon: 'start-icon.webp', content: {intro: 'Ein Gelenk ist eine stabile Verbindung von zwei oder mehr Knochen.', media: '', headline1: 'Aufgabe', media1: '', text1: 'Das Gelenk gibt Richtung und Führung. Es ist verantwortlich für die Zentrierung und die Position der Knochen zueinander und der Position des Körpers im Raum. ', headline2: '', media2: '', text2: 'Gelenke sind auch der Ort der Bewegung (Roll - Gleit – Bewegung): Es muss darauf geachtet werden, dass Gelenke frei von Druck sind und diese sich nicht versteifen.', headline3: 'Qualität', media3: '', text3: 'Nach Ayurveda ist die Qualität der Gelenkmarmas: glatt, fliesend, beweglich, ölig.', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Gelenk Marmas_Gelenkarten', order: 44, topic: 'Gelenk Marmas', category: 'marmas', lesson: 'Gelenkarten', icon: 'anatomy-icon.webp', content: {intro: 'Es gibt 6 verschiedene Gelenkarten im Menschlichen Körper:', media: '', headline1: 'Planes Gelenk (z.B. Mittelfuß-/Handwurzel-/Kiefergelenk)', media1: '', text1: '', headline2: 'Scharniergelenk (z.B. Fingermittel-/endgliedgelenk)', media2: '', text2: '', headline3: 'Zapfengelenk (Ellenbogengelenk)', media3: '', text3: '', headline4: 'Eigelenk (z.B. Handgelenk)', media4: '', text4: '', headline5: 'Sattelgelenk (z.B. Daumenwurzelgelenk)', media5: '', text5: '', headline6: 'Kugelgelenk (z.B. Hüftgelenk → größte Stabilität erforderlich: große Pfanne)', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Gelenk Marmas_Aufbau', order: 45, topic: 'Gelenk Marmas', category: 'marmas', lesson: 'Aufbau', icon: 'anatomy-icon.webp', content: {intro: '', media: '', headline1: '', media1: '', text1: '', headline2: '', media2: '', text2: '', headline3: '', media3: '', text3: '', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Kommunikation_Intro', order: 46, topic: 'Kommunikation', category: 'yoga', lesson: 'Intro', icon: 'intro-icon.webp', content: {intro: 'Man kann nicht nicht Kommunizieren.', media: '', headline1: '', media1: '', text1: 'Nicht nur das gesprochene Wort, sondern auch Betonung, Gestik und Mimik und andere äßere Aspekte sind Kommunikation.', headline2: '', media2: '', text2: 'Auch im Yoga ist kommunikation wichtig, zum einen zwischen der Übenden und anleitenden person, aber auch der innere Dialog.', headline3: '', media3: '', text3: 'Im Folgenden lernen wir ein Kommunikationsmodell kennen und ein paar Tips, wie klare Kommunikation funktionieren kann.', headline4: '', media4: '', text4: '', headline5: '', media5: '', text5: '', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },
{ id: 'Kommunikation_Kommunikations-madell', order: 47, topic: 'Kommunikation', category: 'yoga', lesson: 'Kommunikations- madell', icon: '', content: {intro: 'Ein bekanntes Kommunikationsmodell ist das Kommunikationsquadrat von Schulz von Thun.', media: '', headline1: '', media1: '', text1: 'Er beschreibt in seinem Modell, dass jede Kommunikation immer gleichzeitig vier Bestandteile hat.', headline2: '', media2: '<ul><li>eine Sachinformation (worüber ich informiere)</li><li>eine Selbstkundgabe (was ich von mir zu erkennen gebe)</li><li>einen Beziehungshinweis (was ich von dir halte und wie ich zu dir stehe)</li><li>einen Appell (was ich bei dir erreichen möchte)</li></ul>', text2: '', headline3: '', media3: '', text3: 'Diese vier Dimensionen hat Shulz von Thun in einem Quadrat dargestellt, bei dem der Sender diese vier Botschaften sendet und der Empfäger mit vier Ohren diese empfängt.', headline4: 'Das Geber und Nehmer Modell.', media4: '', text4: 'Dr. Roland Lüthi hat darauf aufbauend das Modell erweitert.', headline5: '', media5: '', text5: 'Der Informationsgeber gibt die Botschaft bestehend aus den vier Dimensionen Sachinhalt, Appell, Beziehung und Selbstoffenbarung. Der Informationsnehmer nimmt sich die Information, allerdings muss dies nicht genau der gegebenen Information entsprechen. Der Nehmer kann zum Beispiel den Appell stärker wahrnehmen, die anderen Dimensionen schwächer, als vom Geber beabsichtigt. In einem anderen Fall könnte der Nehmer die Beziehungsebene anders deuten als der Geber.', headline6: '', media6: '', text6: 'Die Dimensionen zwischen Geber und Nehmer müssen nicht genau deckungsgleich sein. Die folge ist eine Unsymetrie in der Kommuination, Missverständnisse können die Folge sein.', outro: '', quote: ''}  },
{ id: 'Kommunikation_Kommunikation', order: 48, topic: 'Kommunikation', category: 'yoga', lesson: 'Kommunikation', icon: '', content: {intro: 'In der Kommunikation kann nicht davon ausgegangen werden, dass der Informations Empfänger die Botschaten so aufnimmt wie vom Informationsgeber beabsichtigt. ', media: '', headline1: '', media1: '', text1: 'Der Informationsnehmer ist durch seine eignen Erfahrungen und Umwelt geprägt und interpretiert die Botschaften daher anders. Fehlkommunikation und Missverständnisse sind die Folge. Eine möglichst klare Komminikation mit wenig Interpretationsspielraum ist daher wichtig.', headline2: 'Weichmacher', media2: '', text2: 'Um eine klare Botschaften zu senden müssen "Weichmacher" vermieden werden. Weichmacher sind zum Beispiel:', headline3: '', media3: '<ul><li>vielleicht</li><li>eigentlich</li><li>eventuell</li><li>wahrscheinlich</li></ul>', text3: 'Außerdem die Benutzung des Konjunktiv oder Einleitungssätze wie "wenn ich das richtig verstanden habe".', headline4: 'Die Botschaft "Aber"', media4: '', text4: 'Antwortet man seinem Gegenüber mit "aber ..." ist das “Aber” gleichbedeutend mit einer Vereinung von allem was der Gesprächspartner vorher gesagt hat. Dies führt zu ungewollter Konfrontation.', headline5: '', media5: '', text5: 'Um das Argument des Gegenübers nicht direkt zu nigieren, den eigenen Aspekt mit anzuführen kann mit verbindenden Elementen an die Konversation mit "und", "außerdem" oder "gleichzeitig" angeknüpft werden.', headline6: '', media6: '', text6: '', outro: '', quote: ''}  },

		];
        const initialMarmaData = [
{ id: 'kurca_ll', marmaName: {sanskrit: 'kūrca', de: 'Mittelfuß-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'Zehengrundgelenke', height: '0', explanation: 'kurz vor den Zehengelenkskapseln, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्च ', origin: 'Bündel, Bündel Gras, Resigbesen'}  },
{ id: 'kurca_rl', marmaName: {sanskrit: 'kūrca', de: 'Mittelfuß-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'Zehengrundgelenke', height: '0', explanation: 'kurz vor den Zehengelenkskapseln, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्च ', origin: 'Bündel, Bündel Gras'}  },
{ id: 'kurca_la', marmaName: {sanskrit: 'kūrca', de: 'Mittelhand-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'Mittelhand', height: '850', explanation: 'kurz vor den Fingergelenkskapseln, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्च ', origin: 'Bündel, Bündel Gras'}  },
{ id: 'kurca_ra', marmaName: {sanskrit: 'kūrca', de: 'Mittelhand-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'Mittelhand', height: '850', explanation: 'kurz vor den Fingergelenkskapseln, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्च ', origin: 'Bündel, Bündel Gras'}  },
{ id: 'kurcaS_ll', marmaName: {sanskrit: 'kūrcaśiras', de: 'Fußwurzel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'Fußwurzel', height: '0', explanation: 'an den Fußwurzelknochen und spannt sich wie ein Bogen, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्चशिरस् ', origin: 'Kūrcaśiras besteht aus kūrca (Bündel) und śiras (der Kopf)'}  },
{ id: 'kurcaS_rl', marmaName: {sanskrit: 'kūrcaśiras', de: 'Fußwurzel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'Fußwurzel', height: '0', explanation: 'an den Fußwurzelknochen und spannt sich wie ein Bogen, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्चशिरस् ', origin: 'Kūrcaśiras besteht aus kūrca (Bündel) und śiras (der Kopf)'}  },
{ id: 'kurcaS_la', marmaName: {sanskrit: 'kūrcaśiras', de: 'Handwurzel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'Handwurzel', height: '850', explanation: 'an den Handwurzelknochen und spannt sich wie ein Bogen, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्चशिरस् ', origin: 'Kūrcaśiras besteht aus kūrca (Bündel) und śiras (der Kopf)'}  },
{ id: 'kurcaS_ra', marmaName: {sanskrit: 'kūrcaśiras', de: 'Handwurzel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'Handwurzel', height: '850', explanation: 'an den Handwurzelknochen und spannt sich wie ein Bogen, vorstellbar wie der Bund enes Reisigbesens'} , info: {typography: 'कूर्चशिरस् ', origin: 'Kūrcaśiras besteht aus kūrca (Bündel) und śiras (der Kopf)'}  },
{ id: 'ani_ll', marmaName: {sanskrit: 'āṇi', de: 'Beinkraft-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'linker Oberschenkel', height: '430', explanation: 'an der Bündelung des Quadrizeps, ca. eine Handbreit über dem Knie'} , info: {typography: 'आणि', origin: 'Zapfen der Wagenachse'}  },
{ id: 'ani_rl', marmaName: {sanskrit: 'āṇi', de: 'Beinkraft-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'rechter Oberschenkel', height: '430', explanation: 'an der Bündelung des Quadrizeps, ca. eine Handbreit über dem Knie'} , info: {typography: 'आणि', origin: 'Zapfen der Wagenachse'}  },
{ id: 'ani_la', marmaName: {sanskrit: 'āṇi', de: 'Armkraft-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'linker Oberarm', height: '1100', explanation: 'an der Bündelung des Triezeps, ca. eine Handbreit über dem Ellenbogen'} , info: {typography: 'आणि', origin: 'Zapfen der Wagenachse'}  },
{ id: 'ani_ra', marmaName: {sanskrit: 'āṇi', de: 'Armkraft-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'rechter Oberarm', height: '1100', explanation: 'an der Bündelung des Triezeps, ca. eine Handbreit über dem Ellenbogen'} , info: {typography: 'आणि', origin: 'Zapfen der Wagenachse'}  },
{ id: 'kakshadara_l', marmaName: {sanskrit: 'kakṣadhara ', de: 'Oberste-Rippe-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'linke unterste Rippe bis linke oberste Rippe', height: '1000', explanation: 'an der Körperflanke bis hoch zur obersten Rippe. Vorspellbar wie ein Scherengitter aus Sehnen zwischen den Rippen'} , info: {typography: 'कक्षधर ', origin: ''}  },
{ id: 'kakshadara_r', marmaName: {sanskrit: 'kakṣadhara ', de: 'Oberste-Rippe-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'rechte unterste Rippe bis rechte oberste Rippe', height: '1000', explanation: 'an der Körperflanke bis hoch zur obersten Rippe. Vorspellbar wie ein Scherengitter aus Sehnen zwischen den Rippen'} , info: {typography: 'कक्षधर ', origin: ''}  },
{ id: 'ksipra_ll', marmaName: {sanskrit: 'kṣipra ', de: 'Fußwinkel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'Fußwinkel (zwischen Großer- und Zeigezehe)', height: '0', explanation: 'zwischen Großer- und Zeigezehe'} , info: {typography: 'क्षिप्र ', origin: ''}  },
{ id: 'ksipra_rl', marmaName: {sanskrit: 'kṣipra ', de: 'Fußwinkel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'Fußwinkel (zwischen Großer- und Zeigezehe)', height: '0', explanation: 'zwischen Großer- und Zeigezehe'} , info: {typography: 'क्षिप्र ', origin: ''}  },
{ id: 'ksipra_la', marmaName: {sanskrit: 'kṣipra ', de: 'Handwinkel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'Handwinkel (zwischen Daumen und Zeigefinger)', height: '850', explanation: 'zwischen Daumen und Zeigefinger'} , info: {typography: 'क्षिप्र ', origin: 'schnell'}  },
{ id: 'ksipra_ra', marmaName: {sanskrit: 'kṣipra ', de: 'Handwinkel-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'Handwinkel (zwischen Daumen und Zeigefinger)', height: '850', explanation: 'zwischen Daumen und Zeigefinger'} , info: {typography: 'क्षिप्र ', origin: 'schnell'}  },
{ id: 'amsa_la', marmaName: {sanskrit: 'aṃsa', de: 'Schulterhöhe-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'Schulterdach', height: '1400', explanation: 'am Schulterdach über der Oberarmkugel, an der gedachten Verlängerung des Schlüsselbeins'} , info: {typography: 'अंस', origin: 'Schulter'}  },
{ id: 'amsa_ra', marmaName: {sanskrit: 'aṃsa', de: 'Schulterhöhe-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'Schulterdach', height: '1400', explanation: 'am Schulterdach über der Oberarmkugel, an der gedachten Verlängerung des Schlüsselbeins'} , info: {typography: 'अंस', origin: 'Schulter'}  },
{ id: 'basti', marmaName: {sanskrit: 'basti', de: 'Blasen-Marma'} , marmaGrp: {sanskrit: 'snayu', de: 'Sehnenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'mittig', anatomy: 'Blase', height: '850', explanation: ''} , info: {typography: 'बस्ति', origin: ''}  },
{ id: 'gulpha_ll', marmaName: {sanskrit: 'gulpha ', de: 'Fußgelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'linkes Fußgelenk', height: '0', explanation: 'im Gelenk zwischen Fuß und Unterschenkel'} , info: {typography: 'गुल्फ ', origin: 'Knöchel oder auch zwei'}  },
{ id: 'gulpha_rl', marmaName: {sanskrit: 'gulpha ', de: 'Fußgelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'rechtes Fußgelenk', height: '0', explanation: 'im Gelenk zwischen Fuß und Unterschenkel'} , info: {typography: 'गुल्फ ', origin: 'Knöchel oder auch zwei'}  },
{ id: 'manibandha_la', marmaName: {sanskrit: 'maṇibandha', de: 'Handgelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'linkes Handgelenk', height: '850', explanation: 'im Gelenk zwischen Hand und Unterarm'} , info: {typography: 'मणिबन्ध ', origin: 'Anlegung von Juwelen (maṇi = juwelen)'}  },
{ id: 'manibandha_ra', marmaName: {sanskrit: 'maṇibandha', de: 'Handgelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'rechtes Handgelenk', height: '850', explanation: 'im Gelenk zwischen Hand und Unterarm'} , info: {typography: 'मणिबन्ध ', origin: 'Anlegung von Juwelen (maṇi = juwelen)'}  },
{ id: 'kukundara_l', marmaName: {sanskrit: 'kukundara', de: 'Hüftgelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'linkes Hüftgelenk', height: '850', explanation: 'im Gelenk zwischen Oberschenkel und Hüftknochen. Querachse zwischen den beiden Punkten links und rechts ca. 3 Finger über dem Rollhügel'} , info: {typography: 'कुकुन्दर', origin: 'Kundara = Höhle, Höhler der Lenden.'}  },
{ id: 'kukundara_r', marmaName: {sanskrit: 'kukundara', de: 'Hüftgelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'rechtes Hüftgelenk', height: '850', explanation: 'im Gelenk zwischen Oberschenkel und Hüftknochen. Querachse zwischen den beiden Punkten links und rechts ca. 3 Finger über dem Rollhügel'} , info: {typography: 'कुकुन्दर', origin: 'Kundara = Höhle, Höhler der Lenden.'}  },
{ id: 'janu_ll', marmaName: {sanskrit: 'jānu', de: 'Kniegelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'linkes Kniegelenk', height: '430', explanation: 'im Gelenk zwischen Oberschenkelknochen und Schien- und Wadenbein'} , info: {typography: 'जानु', origin: ''}  },
{ id: 'janu_rl', marmaName: {sanskrit: 'jānu', de: 'Kniegelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'rechtes Kniegelenk', height: '430', explanation: 'im Gelenk zwischen Oberschenkelknochen und Schien- und Wadenbein'} , info: {typography: 'जानु', origin: ''}  },
{ id: 'kurpara_la', marmaName: {sanskrit: 'kūrpara', de: 'Ellenbogengelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'linker Ellenbogen', height: '1000', explanation: 'im Gelenk zwischen Oberarmknochen und Elle und Speiche'} , info: {typography: 'कूर्पर', origin: ''}  },
{ id: 'kurpara_ra', marmaName: {sanskrit: 'kūrpara', de: 'Ellenbogengelenk-Marma'} , marmaGrp: {sanskrit: 'sandhi', de: 'Gelenkmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'rechter Ellenbogen', height: '1000', explanation: 'im Gelenk zwischen Oberarmknochen und Elle und Speiche'} , info: {typography: 'कूर्पर', origin: ''}  },
{ id: 'indravasti_ll', marmaName: {sanskrit: 'indravasti', de: 'Wadenmitte-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'Wadenmuskel', height: '100', explanation: 'tiefliegend in der Mitte der Wadenmuskulatur'} , info: {typography: 'इन्द्रवस्ति ', origin: 'Indra = Gottheit, vasti = innewohnen '}  },
{ id: 'indravasti_rl', marmaName: {sanskrit: 'indravasti', de: 'Wadenmitte-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'Wadenmuskel', height: '100', explanation: 'tiefliegend in der Mitte der Wadenmuskulatur'} , info: {typography: 'इन्द्रवस्ति ', origin: 'Indra = Gottheit, vasti = innewohnen '}  },
{ id: 'indravasti_la', marmaName: {sanskrit: 'indravasti', de: 'Unterarmmitte-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'Unterarmmuskel', height: '890', explanation: 'tiefliegend in der Mitte der Unterarmmuskulatur'} , info: {typography: 'इन्द्रवस्ति ', origin: 'Indra = Gottheit, vasti = innewohnen '}  },
{ id: 'indravasti_ra', marmaName: {sanskrit: 'indravasti', de: 'Unterarmmitte-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'Unterarmmuskel', height: '890', explanation: 'tiefliegend in der Mitte der Unterarmmuskulatur'} , info: {typography: 'इन्द्रवस्ति ', origin: 'Indra = Gottheit, vasti = innewohnen '}  },
{ id: 'talahridaya_ll', marmaName: {sanskrit: 'talahṛdaya', de: 'Fußsohlen-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'linke Fußsohle', height: '0', explanation: 'in der Fußsohlenmuskulatur. Vorstellbar wie ein weiches Ausbreiten aus der Fußsohlenmitte'} , info: {typography: 'तलहृदय ', origin: 'tala = Oberfläche und hṛdaya =Herz'}  },
{ id: 'talahridaya_rl', marmaName: {sanskrit: 'talahṛdaya', de: 'Fußsohlen-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'rechte Fußsohle', height: '0', explanation: 'in der Fußsohlenmuskulatur. Vorstellbar wie ein weiches Ausbreiten aus der Fußsohlenmitte'} , info: {typography: 'तलहृदय ', origin: ''}  },
{ id: 'talahridaya_la', marmaName: {sanskrit: 'talahṛdaya', de: 'Handflächen-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'linke Handfläche', height: '850', explanation: 'in der Handflächenmuskulatur. Vorstellbar wie ein weiches Ausbreiten aus der Handflächenmitte'} , info: {typography: 'तलहृदय ', origin: ''}  },
{ id: 'talahridaya_ra', marmaName: {sanskrit: 'talahṛdaya', de: 'Handflächen-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'rechte Handfläche', height: '850', explanation: 'in der Handflächenmuskulatur. Vorstellbar wie ein weiches Ausbreiten aus der Handflächenmitte'} , info: {typography: 'तलहृदय ', origin: ''}  },
{ id: 'stanarohita_l', marmaName: {sanskrit: 'stanarohita', de: 'Brustkorbaufrichtungs-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'rechts auf der Vorderseite des Brustkorps oberhalb der Brustwarze', height: '1350', explanation: ''} , info: {typography: 'स्तनरोहित', origin: ''}  },
{ id: 'stanarohita_r', marmaName: {sanskrit: 'stanarohita', de: 'Brustkorbaufrichtungs-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'links auf der Vorderseite des Brustkorps oberhalb der Brustwarze', height: '1350', explanation: ''} , info: {typography: 'स्तनरोहित', origin: ''}  },
{ id: 'guda', marmaName: {sanskrit: 'guḍa', de: 'Beckenboden-Marma'} , marmaGrp: {sanskrit: 'mamsa', de: 'Muskelmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'mittig', anatomy: 'Beckenboden', height: '840', explanation: 'umfasst den Bereich Rektum, bzw. Anus'} , info: {typography: 'गुद', origin: ''}  },
{ id: 'urvi_ll', marmaName: {sanskrit: 'urvī', de: 'Oberschenkelmitte-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'innenseite des linken Beins', height: '500', explanation: 'an der Innenseite des linken Oberschenkels. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberarms'} , info: {typography: 'उर्वी ', origin: 'Land, Erde'}  },
{ id: 'urvi_rl', marmaName: {sanskrit: 'urvī', de: 'Oberschenkelmitte-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'innenseite des rechten Beins', height: '500', explanation: 'an der Innenseite des rechten Oberschenkels. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberarms'} , info: {typography: 'उर्वी ', origin: 'Land, Erde'}  },
{ id: 'bahvi_la', marmaName: {sanskrit: 'bāhvī', de: 'Oberarmmitte-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'innenseite des linken Arms', height: '1120', explanation: 'an der Innenseite des linken Oberarms. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberarms'} , info: {typography: 'बाह्वी', origin: 'Arm'}  },
{ id: 'bahvi_ra', marmaName: {sanskrit: 'bāhvī', de: 'Oberarmmitte-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'innenseite des rechten Arms', height: '1120', explanation: 'an der Innenseite des rechten Oberarms. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberarms'} , info: {typography: 'बाह्वी', origin: 'Arm'}  },
{ id: 'lohitaksha_ll', marmaName: {sanskrit: 'lohitākṣa', de: 'Beinblutfluss-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'Unterhalb des Leistenwinkels an der Oberschenkelwurzel', height: '700', explanation: 'an der Innenseite des linken Oberschenkelansatzes. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberschenkels'} , info: {typography: 'लोहिताक्ष', origin: 'rotes Auge'}  },
{ id: 'lohitaksha_rl', marmaName: {sanskrit: 'lohitākṣa', de: 'Beinblutfluss-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'Unterhalb des Leistenwinkels an der Oberschenkelwurzel', height: '700', explanation: 'an der Innenseite des rechten Oberschenkelansatzes. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberschenkels'} , info: {typography: 'लोहिताक्ष', origin: 'rotes Auge'}  },
{ id: 'lohitaksha_la', marmaName: {sanskrit: 'lohitākṣa', de: 'Armblutfluss-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Arm', bodySide: 'links', anatomy: 'Unterhalb der Achselhöle an der Oberarmwurzel', height: '1200', explanation: 'an der Innenseite des linken Oberarmansatzes. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberarms'} , info: {typography: 'लोहिताक्ष', origin: 'rotes Auge'}  },
{ id: 'lohitaksha_ra', marmaName: {sanskrit: 'lohitākṣa', de: 'Armblutfluss-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Arm', bodySide: 'rechts', anatomy: 'Unterhalb der Achselhöle an der Oberarmwurzel', height: '1200', explanation: 'an der Innenseite des rechten Oberarmansatzes. An dem Ort verlaufen Blutbahnen und Nervenstränge in einer Muskelloge des Oberarms'} , info: {typography: 'लोहिताक्ष', origin: 'rotes Auge'}  },
{ id: 'vitapa_ll', marmaName: {sanskrit: 'viṭapa', de: 'Leisten-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Bein', bodySide: 'links', anatomy: 'linke Leistengegend', height: '700', explanation: 'am Übergang zwischen Rumpf und Bein in der Leistengegend, bzw. An der inneren Gesäßfalte über dem Oberschenkel'} , info: {typography: 'विटप', origin: 'Ast oder Zweig'}  },
{ id: 'vitapa_rl', marmaName: {sanskrit: 'viṭapa', de: 'Leisten-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Bein', bodySide: 'rechts', anatomy: 'rechte Leistengegend', height: '700', explanation: 'am Übergang zwischen Rumpf und Bein in der Leistengegend, bzw. An der inneren Gesäßfalte über dem Oberschenkel'} , info: {typography: 'विटप', origin: 'Ast oder Zweig'}  },
{ id: 'stanamula_l', marmaName: {sanskrit: 'stanamūla', de: 'Bruskorbboden-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'linker unterer Brustkorb vorne', height: '1080', explanation: 'am linken Rippenbogen, von der seitlichen Spitze der linken, untersten Rippe bis zum Brustbein. Auf einer Höhe mit dem am Rücken befindende bṛhatī'} , info: {typography: 'स्तनमूल', origin: 'Wurzel der Brust'}  },
{ id: 'stanamula_r', marmaName: {sanskrit: 'stanamūla', de: 'Bruskorbboden-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'rechter unterer Brustkorb vorne', height: '1080', explanation: 'am rechten Rippenbogen, von der seitlichen Spitze der rechten, untersten Rippe bis zum Brustbein. Auf einer Höhe mit dem am Rücken befindende bṛhatī'} , info: {typography: 'स्तनमूल', origin: 'Wurzel der Brust'}  },
{ id: 'parsvasandhi_l', marmaName: {sanskrit: 'pārśvasandhi', de: 'Rippen-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'oberhalb der rechten Niere', height: '1100', explanation: 'am rechten hinteren Rumpf oberhalb der Niere'} , info: {typography: 'सन्धिपार्श्व', origin: 'pārśva = Seiten; sandhi = Verbindung, Gelenke'}  },
{ id: 'parsvasandhi_r', marmaName: {sanskrit: 'pārśvasandhi', de: 'Rippen-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'oberhalb der linken Niere', height: '1100', explanation: 'am linken hinteren Rumpf oberhalb der Niere'} , info: {typography: 'सन्धिपार्श्व', origin: 'pārśva = Seiten; sandhi = Verbindung, Gelenke'}  },
{ id: 'brhati_l', marmaName: {sanskrit: 'bṛhatī', de: 'Rückenstreck-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'Mitte des Rückens, links der Bruswirbelsäule', height: '1080', explanation: 'auf eine Höhe mit dem am vorderen Brustkorp befindlichen stanamūla'} , info: {typography: 'बृहती ', origin: ''}  },
{ id: 'brhati_r', marmaName: {sanskrit: 'bṛhatī', de: 'Rückenstreck-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'Mitte des Rückens, rechts der Bruswirbelsäule', height: '1080', explanation: 'auf eine Höhe mit dem am vorderen Brustkorp befindlichen stanamūla'} , info: {typography: 'बृहती ', origin: ''}  },
{ id: 'apastambha_l', marmaName: {sanskrit: 'apastambha', de: 'Lungepforte / Lungenstütze'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'linker Hauptbronchus', height: '1120', explanation: 'mittig im Brustkorb, von vorne betrachtet links des Brustbeins. Dieser Ort beschreibt die erste Gabelung der Luftröhre um den linken Lungenflügel mit Luft zu versorgen.'} , info: {typography: 'अपस्तम्भ', origin: 'apa = weg / hinab, stambha = geführt, stabil'}  },
{ id: 'apastambha_r', marmaName: {sanskrit: 'apastambha', de: 'Lungepforte / Lungenstütze'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'rechter Hauptbronchus', height: '1120', explanation: 'mittig im Brustkorb, von vorne betrachtet rechts des Brustbeins. Dieser Ort beschreibt die erste Gabelung der Luftröhre um den rechten Lungenflügel mit Luft zu versorgen.'} , info: {typography: 'अपस्तम्भ', origin: 'apa = weg / hinab, stambha = geführt, stabil'}  },
{ id: 'nabhi', marmaName: {sanskrit: 'nābhi', de: 'Nabel-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'mittig', anatomy: 'Nabel', height: '890', explanation: ''} , info: {typography: 'नाभि', origin: ''}  },
{ id: 'hrdaya', marmaName: {sanskrit: 'hṛdaya', de: 'Herz-Marma'} , marmaGrp: {sanskrit: 'sira', de: 'Blutgefäßmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'mittig', anatomy: 'Herz', height: '1200', explanation: ''} , info: {typography: 'हृदय', origin: ''}  },
{ id: 'nitamba_l', marmaName: {sanskrit: 'nitamba', de: 'Hüftknochen-Marma'} , marmaGrp: {sanskrit: 'asthi', de: 'Knochenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'Mitte der linken Beckenschaufel', height: '840', explanation: 'in der Mitte der Beckenschaufen. Vorstellbar wie der Punkt an dem das Becken gleichmäßig aufgerichtet werden kann'} , info: {typography: 'नितम्ब ', origin: 'das Gesäß'}  },
{ id: 'nitamba_r', marmaName: {sanskrit: 'nitamba', de: 'Hüftknochen-Marma'} , marmaGrp: {sanskrit: 'asthi', de: 'Knochenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'Mitte der rechten Beckenschaufel', height: '840', explanation: 'in der Mitte der Beckenschaufen. Vorstellbar wie der Punkt an dem das Becken gleichmäßig aufgerichtet werden kann'} , info: {typography: 'नितम्ब ', origin: 'das Gesäß'}  },
{ id: 'amsaphalaka_l', marmaName: {sanskrit: 'aṃsaphalaka', de: 'Schulterblatt-Marma'} , marmaGrp: {sanskrit: 'asthi', de: 'Knochenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'Mitte des linken Schulterblatts', height: '1230', explanation: 'in der Mitte des Schulterblatts'} , info: {typography: 'अंसफलक ', origin: 'oberer Teil der Wirbelsäule, Schulterblatt'}  },
{ id: 'amsaphalaka_r', marmaName: {sanskrit: 'aṃsaphalaka', de: 'Schulterblatt-Marma'} , marmaGrp: {sanskrit: 'asthi', de: 'Knochenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'Mitte des rechten Schulterblatts', height: '1230', explanation: 'in der Mitte des Schulterblatts'} , info: {typography: 'अंसफलक ', origin: 'oberer Teil der Wirbelsäule, Schulterblatt'}  },
{ id: 'katikataruna_l', marmaName: {sanskrit: 'kaṭīkataruṇa', de: 'Kreutzbein-Darmbein-Marma'} , marmaGrp: {sanskrit: 'asthi', de: 'Knochenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'links', anatomy: 'unterer Rücken links vom Kreuzbein', height: '850', explanation: ''} , info: {typography: 'कटीकतरुण ', origin: ''}  },
{ id: 'katikataruna_r', marmaName: {sanskrit: 'kaṭīkataruṇa', de: 'Kreutzbein-Darmbein-Marma'} , marmaGrp: {sanskrit: 'asthi', de: 'Knochenmarma'} , location: {bodyRegion: 'Rumpf', bodySide: 'rechts', anatomy: 'unterer Rücken links vom Kreuzbein', height: '850', explanation: ''} , info: {typography: 'कटीकतरुण ', origin: ''}  },

		];

		request.onupgradeneeded = (event) => {
			db = event.target.result;
			console.log("Updating Database ...");

			// Create "knowledgeStore" if it doesn't exist
			if (!db.objectStoreNames.contains("knowledgeStore")) {
				console.log("creating knowledgeStore ...");
				let knowledgeStore = db.createObjectStore("knowledgeStore", { keyPath: "id" });
				knowledgeStore.createIndex('topic', 'topic', { unique: false });
				knowledgeStore.createIndex('lesson', 'lesson', { unique: false });
				knowledgeStore.createIndex('order', 'order', { unique: false });
				knowledgeStore.createIndex('category', 'category', { unique: false });
				knowledgeStore.createIndex('content', [
					"intro", "media1", "text1", "media2", "text2", "media3", "text3", "media4", "text4", "media5", "text5"
				], { unique: false });

				initialKnowledgeData.forEach((lesson) => {
					knowledgeStore.put(lesson);
				});
			}

			// Create "progressStore" if it doesn't exist
			if (!db.objectStoreNames.contains("progressStore")) {
				console.log("creating progressStore ...");
				let progressStore = db.createObjectStore("progressStore", { keyPath: "id" });
				progressStore.createIndex('topic', 'topic', { unique: false });
				progressStore.createIndex('order', 'order', { unique: false });
				progressStore.createIndex('done', 'done', { unique: false });
				progressStore.createIndex('favorite', 'favorite', { unique: false });

				initialKnowledgeData.forEach((lesson) => {
					progressStore.put({ id: lesson.id, topic: lesson.topic, order: lesson.order, done: false, favorite: false });
				});
			}

			// Create "marmaStore" if it doesn't exist
			if (!db.objectStoreNames.contains("marmaStore")) {
				console.log("creating marmaStore ...");
				let marmaStore = db.createObjectStore("marmaStore", { keyPath: "id" });
				marmaStore.createIndex('marmaName', ["sanskrit", "de"], { unique: false });
				marmaStore.createIndex('marmaGrp', ["sanskrit", "de"], { unique: false });
				marmaStore.createIndex('location', ["bodyRegion", "anatomy", "height", "explanation"], { unique: false });
				marmaStore.createIndex('info', ["typography", "origin"], { unique: false });

				initialMarmaData.forEach((marma) => {
					marmaStore.put(marma);
				});
			}

			// Create "marmaValueStore" if it doesn't exist
			if (!db.objectStoreNames.contains("marmaValueStore")) {
				console.log("creating marmaValueStore ...");
				let marmaValueStore = db.createObjectStore("marmaValueStore", { keyPath: "id" });
				marmaValueStore.createIndex('localisation', 'localisation', { unique: false });
				marmaValueStore.createIndex('awareness', 'awareness', { unique: false });
				marmaValueStore.createIndex('frequency', 'frequency', { unique: false });

				initialMarmaData.forEach((marma) => {
					marmaValueStore.put({ id: marma.id, localisation: 0, awareness: 0, frequency: 0 });
				});
			}
		};

		request.onsuccess = (event) => {
			console.log("Loading Database ...");
			db = event.target.result;
			console.log("Database OPEN");

			// Create a transaction for both knowledgeStore and progressStore
			const transaction = db.transaction(["knowledgeStore", "progressStore"], "readwrite");

			const knowledgeStore = transaction.objectStore("knowledgeStore");
			const progressStore = transaction.objectStore("progressStore");
			const marmaStore = getObjectStore(db, "marmaStore", "readwrite");


			// Update knowledgeStore every time
			initialKnowledgeData.forEach((lesson) => {
				knowledgeStore.put(lesson);
			});

			// Retrieve all lessons from knowledgeStore
			const knowledgeRequest = knowledgeStore.getAll();
			knowledgeRequest.onsuccess = (event) => {
				const knowledgeData = event.target.result;
				knowledgeData.forEach((lesson) => {
					const progressRequest = progressStore.get(lesson.id);
					progressRequest.onsuccess = (event) => {
						const progressData = event.target.result;
						if (!progressData) {
							// If progressData doesn't exist, create a new entry with default values
							progressStore.put({
								id: lesson.id,
								order: lesson.order,
								done: false,
								favorite: false
							});
						} else {
							// If progressData exists, only update the order without overwriting done and favorite
							progressData.order = lesson.order;
							progressStore.put(progressData);
						}
					};
					progressRequest.onerror = (event) => {
						console.error("Error accessing progressStore:", event.target.errorCode);
					};
				});
			};

			knowledgeRequest.onerror = (event) => {
				console.error("Error accessing knowledgeStore:", event.target.errorCode);
			};

			// Update marmaStore every time
            initialMarmaData.forEach((marma) => {
                marmaStore.put(marma);
            });

			transaction.oncomplete = () => {
				console.log("Transaction complete");
			};

			transaction.onerror = (event) => {
				console.error("Transaction error: ", event.target.errorCode);
			};
		resolve(db);
		};
	});
}

function getObjectStore(db, store_name, mode) {
    const transaction = db.transaction([store_name], mode);
    return transaction.objectStore(store_name);
}

initDB()